"use client";

import { useState } from "react";
import { ChevronLeft, ChevronRight, Quote, Sparkles, Star } from "lucide-react";

const testimonials = [
  { name: "Sarah Mitchell", role: "Regular Customer", avatar: "SM", rating: 5, service: "Hair Styling", date: "2 weeks ago", text: "The booking experience was absolutely seamless. I found my favorite stylist, checked availability, and had my appointment confirmed within minutes." },
  { name: "James Chen", role: "Business Professional", avatar: "JC", rating: 5, service: "Deep Tissue Massage", date: "1 month ago", text: "As someone with a packed schedule, I appreciate how easy it is to reschedule appointments. The staff profiles helped me choose the right therapist." },
  { name: "Emily Rodriguez", role: "First-time User", avatar: "ER", rating: 4, service: "Facial Treatment", date: "3 weeks ago", text: "Being able to see real reviews and portfolio photos before choosing a provider gave me so much confidence. My facial treatment was amazing!" },
  { name: "Michael Torres", role: "Monthly Subscriber", avatar: "MT", rating: 5, service: "Beard Grooming", date: "5 days ago", text: "I book my monthly grooming sessions in advance and never have to worry about availability. The whole experience is consistently excellent." },
  { name: "Priya Sharma", role: "Wellness Enthusiast", avatar: "PS", rating: 5, service: "Aromatherapy", date: "1 week ago", text: "The detailed therapist bios and verified certifications make all the difference. I highly recommend this salon to everyone." },
  { name: "David Kim", role: "Corporate Client", avatar: "DK", rating: 4, service: "Corporate Wellness", date: "2 months ago", text: "The group booking feature makes managing wellness appointments effortless. Customer support is responsive and genuinely helpful." },
];

function Card({ testimonial }: { testimonial: (typeof testimonials)[number] }) {
  return <article className="flex h-full flex-col rounded-2xl border border-slate-100 bg-slate-50 p-6 dark:border-slate-800 dark:bg-slate-900 lg:p-8"><span className="mb-5 flex h-10 w-10 items-center justify-center rounded-xl bg-rose-100 text-rose-600 dark:bg-rose-950/30"><Quote size={18} /></span><div className="mb-4 flex gap-0.5">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={16} className={star <= testimonial.rating ? "fill-amber-400 text-amber-400" : "fill-slate-200 text-slate-200"} />)}</div><p className="mb-6 grow text-sm leading-relaxed text-slate-600 dark:text-slate-300">“{testimonial.text}”</p><span className="mb-6 w-fit rounded-lg border border-slate-200 bg-white px-3 py-1 text-xs font-medium text-slate-500 dark:border-slate-700 dark:bg-slate-950">{testimonial.service}</span><div className="flex items-center gap-3 border-t border-slate-200 pt-4 dark:border-slate-700"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-gradient-to-br from-rose-500 to-amber-500 text-sm font-bold text-white">{testimonial.avatar}</span><div><p className="text-sm font-semibold text-slate-900 dark:text-white">{testimonial.name}</p><p className="text-xs text-slate-400">{testimonial.role} · {testimonial.date}</p></div></div></article>;
}

export function TestimonialsSection() {
  const [active, setActive] = useState(0);
  const current = testimonials[active];
  const previous = () => setActive((index) => (index + testimonials.length - 1) % testimonials.length);
  const next = () => setActive((index) => (index + 1) % testimonials.length);
  return <section className="relative overflow-hidden bg-white py-24 dark:bg-slate-950 lg:py-32"><div className="pointer-events-none absolute inset-0"><div className="absolute right-20 top-20 h-[500px] w-[500px] rounded-full bg-rose-50 opacity-60 blur-3xl dark:bg-rose-950/20" /><div className="absolute bottom-20 left-20 h-[400px] w-[400px] rounded-full bg-amber-50 opacity-50 blur-3xl" /></div><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><header className="mb-16 text-center lg:mb-20"><span className="mb-6 inline-flex items-center gap-2 rounded-full bg-rose-50 px-4 py-1.5 text-sm font-medium text-rose-700 ring-1 ring-inset ring-rose-600/10 dark:bg-rose-950/30"><Sparkles size={16} />Client Stories</span><h2 className="mb-6 text-3xl font-bold tracking-tight text-slate-900 dark:text-white md:text-4xl lg:text-5xl">What Our Clients <span className="text-rose-600">Say</span></h2><p className="mx-auto max-w-2xl text-base leading-relaxed text-slate-500 md:text-lg">Join thousands of satisfied customers who trust us for their beauty and wellness appointments every day.</p></header><div className="hidden gap-8 lg:grid lg:grid-cols-3">{testimonials.map((testimonial) => <Card key={testimonial.name} testimonial={testimonial} />)}</div><div className="lg:hidden"><Card testimonial={current} /><div className="mt-6 flex items-center justify-center gap-4"><button type="button" onClick={previous} className="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 text-slate-500 hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600" aria-label="Previous testimonial"><ChevronLeft size={18} /></button><div className="flex gap-2">{testimonials.map((testimonial, index) => <button type="button" key={testimonial.name} onClick={() => setActive(index)} className={`h-2 rounded-full transition-all ${index === active ? "w-6 bg-rose-600" : "w-2 bg-slate-300"}`} aria-label={`Show testimonial ${index + 1}`} />)}</div><button type="button" onClick={next} className="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 text-slate-500 hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600" aria-label="Next testimonial"><ChevronRight size={18} /></button></div></div><div className="mt-20 rounded-2xl bg-slate-900 p-8 md:p-12"><div className="grid grid-cols-2 gap-8 text-center md:grid-cols-4">{[["4.9", "Average Rating", "/5"], ["12,000+", "Happy Clients", ""], ["98%", "Satisfaction Rate", ""], ["3.2K+", "5-Star Reviews", ""]].map(([value, label, suffix]) => <div key={label}><p className="text-3xl font-bold text-white md:text-4xl">{value}<span className="text-lg text-slate-400">{suffix}</span></p><p className="mt-1 text-sm text-slate-400">{label}</p></div>)}</div></div></div></section>;
}
